### ISSUE TITLE
Function to compare 2 bed files

### ISSUE THREAD

**Issue by PatrickWeller** [PatrickWeller/PanelPal#24]
Compare 2 bed files of same panel but different version.
Compare 4th column for casual gene name and output the differences in genes.
Compare the 5th columns for transcript IDs and output the differences in transcripts.

**Comment by PatrickWeller** [comment]
Bed files will only have chr, start, end. So just need to try and compare these columns. Links to User story #58

**Comment by madysonic** [comment]
Related to #18 and #58. Assigned to myself for Sprint 4 as agreed in meeting.

**Comment by madysonic** [comment]
This is basically complete, but needs to be made callable as part of the python package. Happy to have a go at this on Friday.
