### ISSUE TITLE
variant_validator_api_functions.py needs more unit tests.

### ISSUE THREAD

**Issue by madysonic** [PatrickWeller/PanelPal#89]
I think I made an attempt at these early on when I didn't know how to write tests. There is currently very little coverage of testing in this file.

**Comment by PatrickWeller** [comment]
I'll try to do this today @madysonic, as otherwise we can't put the code in main. I thought this was getting done by someone in sprint 3 but must have been missed.

**Comment by PatrickWeller** [comment]
Merged these in #91
