### ISSUE TITLE
Create an environment file 

### ISSUE THREAD

**Issue by madysonic** [PatrickWeller/PanelPal#9]
Create an env.yml file to be used with Conda. Can call the requirements.txt file through the yml.

E.g.:
name: test-env
dependencies:
  - python=3.12.7
  - pip:
    - -r requirements.txt

**Comment by madysonic** [comment]
From the Rubric:

An environment.yaml file that will set-up the environment and a requirements.txt file that can be used to install a minimum basic set of Python modules / libraries using pip

The environment.yaml file must also document any modules installed via conda such that these install when the environment is created

The commands required to build the environment and install modules must be provided in the documentation; 

In addition: the environment.yml and requirements.txt must document the version numbers of key libraries and modules

The number of packages installed by conda are a bare minimum and ideally none, i.e., as many packages as possible must be installed by pip; 

The requirements.txt file has been either replaced by a pyproject.toml or integrated into a pyproject.toml; 

The software must build using the command “pip install .”

**Comment by PatrickWeller** [comment]
We need to head towards this being able to be ran in Docker, but this can be saved for a later sprint

**Comment by ASendellPrice** [comment]
Closing this issue and raising docker containerization as a new issue
